
== capnp-ocaml 2.0.0

=== Backwards-incompatible changes
* Module `Codecs`: change API to accept the more natural `BytesMessage.Message.t`
  instead of `Bytes.t list`.
* Module `Codecs`: change API accept a `compression` specifier, instead of using
  separate functions and separate types for compressed and uncompressed streams.

=== Other changes

* Module `Codecs`: fix incorrect encoding of framing headers (for example,
  as generated by `serialize`).
* Module `Codecs`: fix infinite loop in `PackedStream` decoding.
* Module `Codecs`: correct a packing inefficiency with literal bytes.
* Instantiate `BytesMessage = Message.Make(BytesStorage)`, so the user doesn't always
  need to.
* New module `IO`: functions for moving message data through various types of I/O
  channels.
* Compiler now says something about files it created.
* Corrected compilation errors when using 4.02 `-safe-string`.

== capnp-ocaml 1.0.1

* Avoid use of GNU `install` features in `omake install`.  This corrects installation
  problems on OS X and (most likely) other BSDs.

== capnp-ocaml 1.0.0

* Initial release.

