
== capnp-ocaml 2.0.1

* Invoke OCaml scripts using `-I $OCAML_TOPLEVEL_PATH`, to avoid missing
  `topfind`.

== capnp-ocaml 2.0.0

=== Backwards-incompatible changes
* Module `Codecs`: change API to accept the more natural `BytesMessage.Message.t`
  instead of `Bytes.t list`.
* Module `Codecs`: change API to accept a `compression` specifier, instead of using
  separate functions and separate types for compressed and uncompressed streams.
* Module `Message`: `to_storage` now returns a list of (storage, length) pairs.

=== Other changes
* Module `Codecs`: fix incorrect encoding of framing headers (for example,
  as generated by `serialize`).
* Module `Codecs`: fix infinite loop in `PackedStream` decoding.
* Module `Codecs`: reduce serialized message sizes, by omitting unused allocation
  regions from the serialized messages.
* Instantiate `BytesMessage = Message.Make(BytesStorage)`, so the user doesn't always
  need to. (Implementation is furthermore defunctorized for improved performance.)
* New module `IO`: functions for moving message data through various types of I/O
  channels.
* Compiler now says something about files it created.
* Corrected compilation errors when using 4.02 `-safe-string`.
* Significant performance improvements across the board.

== capnp-ocaml 1.0.1

* Avoid use of GNU `install` features in `omake install`.  This corrects installation
  problems on OS X and (most likely) other BSDs.

== capnp-ocaml 1.0.0

* Initial release.

